data:
  # Raw data path configuration
  raw_data_path: "../data/raw/bangkok_traffy.csv"
  raw_data_columns_path: "raw_data_columns.json"

  # Status mapping configuration
  status_mapping_path: "status.json"

  # Province and Bangkok area name configurations
  province_whitelist_path: "thailand_province_whitelist.json"
  bangkok_official_area_name_path: "bangkok_official_area_name.json"

  # Geographic data path
  bangkok_geographic_data_path: "../data/geographic_data/bangkok_geographic.shp"
  geographic_columns_path: "geographic_columns.json"
  geographic_cleansed_data_path: "../data/processed/cleansed_geo.csv"

scrapping:
  # Population scrapping configuration
  population_scrapping_path: "population_scrapping.json"
  bangkok_index_scrapping_path: "bangkok_index_scrapping.json"
  bangkok_index_scrapped_path: "../data/scrapped/bangkok_index_district_final.csv"

processed:
  # Cleansed data path configuration
  cleansed_data_path: "../data/processed/cleansed_data.csv"
  cleansed_geographic_data_path: "../data/processed/cleansed_geo.csv"