data:
  # Raw data path configuration
  raw_data_path: "../data/raw/bangkok_traffy.csv"
  raw_data_columns_path: "raw_data_columns.json"

  # Status mapping configuration
  status_mapping_path: "status.json"

  # Province and Bangkok area name configurations
  province_whitelist_path: "thailand_province_whitelist.json"
  bangkok_official_area_name_path: "bangkok_official_area_name.json"

  # Geographic data path
  bangkok_geographic_data_path: "../data/geographic_data/bangkok_geographic.shp"
  geographic_columns_path: "geographic_columns.json"